[package]
name = "tests_attrivutes_configuration_conditionalcompilation"
version = "0.1.0"
authors = ["Rafael Costa <rafael.rac.mg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
